#' insertPregnancyEpisodesTable
#'
#' Inserts the identified pregnancy episodes table into a database.
#'
#' @param cdm (`cdm_reference`)
#' @param path (`character(1)`) Path to the generated rds-file generated by `runHipps()`.
#' @param tableName (`character(1)`) Name of the table
#' @param overwrite (`logical(1)`: `TRUE`) If the table should be overwritten or not.
#'
#' @returns (`cdm_reference`)
#' @export
insertPregnancyEpisodesTable <- function(cdm, path, tableName, overwrite = FALSE) {
  # Do checks on result

  pet <- readRDS(path)
  CDMConnector::insertTable(
    cdm = cdm,
    name = tableName,
    table = pet,
    overwrite = overwrite
  )
  return(cdm)
}
